name = Simple - ESD custom layout
description = A simple 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = esd-simple-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer_first]   = Footer First
regions[footer_second]  = Footer Second
regions[footer_third]   = Footer Third

; Stylesheets
stylesheets[all][] = css/layouts/esd-simple/esd-simple.layout.css
