name = ESD home
description = Two columns content, three col footer
preview = preview.png
template = esd-home

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar]        = Sidebar
regions[footer_first]   = Footer First
regions[footer_second]  = Footer Second
regions[footer_third]   = Footer Third

; Stylesheets
stylesheets[all][] = css/layouts/esd-home/esd-home.layout.css
