name = ESD home
description = Two columns content, three col footer
preview = preview.png
template = esd-home

; Regions
regions[branding]       = Below branding
regions[help]           = Help
regions[pre_content]    = Pre-Content
regions[content]        = Content
regions[post_content]   = Post-Content
regions[actions]        = Actions
regions[footer_first]   = Footer First
regions[footer_second]  = Footer Second
regions[footer_third]   = Footer Third
regions[footer_fourth]  = Footer Fourth

; Stylesheets
stylesheets[all][] = css/layouts/esd-home/esd-home.layout.css
